# Generated by Django 4.1.7 on 2023-02-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_image_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="thumbnail",
        ),
    ]
