# Generated by Django 4.1.7 on 2023-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_account"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "account_type"), name="unique_account_for_owner"
            ),
        ),
    ]
