# Generated by Django 4.1.7 on 2023-02-20 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_tier_alter_account_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 20, 21, 13, 29, 914299)
            ),
        ),
    ]
