# Generated by Django 4.1.7 on 2023-02-21 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_image_binary_image_alter_image_link_date_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 21, 11, 29, 38, 476967, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
