# Generated by Django 4.1.7 on 2023-02-21 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_account_tier_alter_image_link_date_expiration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tier",
            name="thumbnails",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 17, 37, 58, 269064)
            ),
        ),
    ]
