# Generated by Django 4.1.7 on 2023-02-21 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_remove_tier_expiring_links_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 21, 18, 1, 50, 444423)
            ),
        ),
    ]
