# Generated by Django 4.1.7 on 2023-02-24 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_image_link_date_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="main.tier",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 24, 17, 55, 17, 760336)
            ),
        ),
    ]
