# Generated by Django 4.1.7 on 2023-02-24 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_image_link_date_expiration_alter_image_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 24, 18, 22, 17, 305317)
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="picture",
            field=models.ImageField(upload_to="images"),
        ),
    ]
