# Generated by Django 4.1.7 on 2023-02-25 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_alter_image_link_date_expiration_alter_image_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnails_data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="link_date_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 25, 20, 31, 4, 921199)
            ),
        ),
    ]
