# Generated by Django 4.1.7 on 2023-02-26 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_image_thumbnails_data_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_for_owner',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='image',
            name='link_date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 21, 16, 27, 52310)),
        ),
    ]
